[versions]
agp = "7.2.2"
androidxActivity = "1.5.0"
androidxCore = "1.8.0"
androidxEspresso = "3.4.0"
androidxLifecycle = "2.5.0"
androidxTestCore = "1.4.0-rc01"
androidxTestJunit = "1.1.3"
androidxWorkManager = "2.7.1"
arrow = "1.1.2"
coil = "2.1.0"
compose = "1.3.0-beta01"
composeCompiler = "1.3.0"
constraintLayout = "1.0.0"
crashlytics = "2.8.1"
detekt = "1.21.0"
firebase = "30.2.0"
gms = "4.3.10"
kermit = "1.1.3"
klock = "3.0.0"
koin = "3.2.0"
koinAnnotations = "1.0.1"
kotlin = "1.7.10"
kotlinCoroutines = "1.6.3"
kotlinSerialization = "1.3.3"
kover = "0.6.0"
ksp = "1.7.10-1.0.6"
ktor = "2.0.3"
material3 = "1.0.0-beta01"
mockk = "1.12.5"
navigation = "2.5.0"
sqlDelight = "2.0.0-alpha03"
turbine = "0.9.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-gms = { module = "com.google.gms:google-services", version.ref = "gms" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kover = { module = "org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin", version.ref = "kover" }

ksp-koin = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotations" }

androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx-test-junit = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestJunit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTestCore" }
androidx-workManager = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWorkManager" }
androidx-workManager-test = { module = "androidx.work:work-testing", version.ref = "androidxWorkManager" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayout"}
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-crashlytics = { module = "co.touchlab:kermit-crashlytics", version.ref = "kermit" }
klock = { module = "com.soywiz.korlibs.klock:klock", version.ref = "klock" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-android-workManager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinAnnotations" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
sqlDelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-sqlite = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqlDelight-sqlite-dialect = { module = "app.cash.sqldelight:sqlite-3-35-dialect", version.ref = "sqlDelight" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
base = [ "arrow-core", "arrow-optics", "kermit", "klock", "koin-annotations", "koin-core", "kotlin-coroutines" ]
compose = [ "androidx-ktx", "coil-compose", "compose-constraintLayout", "compose-ui", "compose-uiToolingPreview", "koin-android-compose", "material3" ]
test-android = [ "androidx-test-core", "androidx-test-junit", "androidx-test-espresso", "compose-uiTest", "koin-test", "koin-test-junit4", "mockk-android" ]
test-kotlin = [ "kotlin-coroutines-test", "kotlin-test-junit", "mockk", "turbine" ]
