name: Test

on: workflow_call

jobs:

  detekt:

    name: Analyze with Detekt
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Detekt analysis
        run: ./gradlew detekt
