name: Deploy apps

on: workflow_call

jobs:

  deploy:
    name: Update dependencies

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Update dependencies
        run: ./gradlew upgradeDependencies -PgitHubWriteToken=${{ secrets.GITHUB_TOKEN }}
