name: Deploy apps

on:
  schedule:
    - cron: "0 13 * * 3"

jobs:

  deploy:
    name: Update dependencies

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v3


      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Update dependencies
        run: ./gradlew upgradeDependencies --stacktrace
        env:
          gitHubWriteToken: ${{ secrets.gitHubWriteToken }}
          gitUserEmail: ${{ secrets.gitUserEmail }}
          gitUserName: ${{ secrets.gitUserName }}
          gitHubRepositoryOwner: ${{ github.repository_owner }}
