name: Run Tests and deploy

on:
  push:
    branches:
      - 'main'

jobs:

  all-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test-action

  deploy:
    needs:
      - all-tests
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/deploy-action
