name: Run Tests and deploy

on:
  push:
    branches:
      - 'main'

jobs:

  all-tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  deploy:
    name: Deploy
    needs: all-tests
    uses: ./.github/workflows/deploy.yml
