name: Run Tests and deploy

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}

jobs:

  setup:
    name: Setup project
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  detekt:
    name: Analyze
    needs: setup
    uses: ./.github/workflows/analyze.yml
    secrets: inherit

  tests:
    name: Tests
    needs: setup
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  instrumented-tests:
    name: Instrumented tests app
    needs: setup
    uses: ./.github/workflows/instrumented-tests.yml
    secrets: inherit

  build:
    name: Build
    needs: setup
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    name: Deploy
    needs:
      - tests
      - instrumented-tests
      - build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
