name: Deploy apps

on: workflow_call

jobs:

  deploy:
    name: Deploy Android app to Play Store

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup google-services json
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > ${GITHUB_WORKSPACE}/app/android/google-services.json

      - name: Setup API keys
        run: |
          echo "${{ secrets.TMDB_KEYS_BASE64 }}" | base64 -d > "${GITHUB_WORKSPACE}"/cinescout/network/tmdb/src/commonMain/kotlin/cinescout/network/tmdb/tmdbKeys.kt &&
          echo "${{ secrets.TRAKT_KEYS_BASE64 }}" | base64 -d > "${GITHUB_WORKSPACE}"/cinescout/network/trakt/src/commonMain/kotlin/cinescout/network/trakt/traktKeys.kt

      - name: Assemble Debug Apk
        run: ./gradlew assembleDebug
        env:
          APP_VERSION: ${{ github.run_number }}

      - name: Assemble Bundle Release
        run: ./gradlew bundleRelease
        env:
          APP_VERSION: ${{ github.run_number }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}

      - name: Upload Release archive
        uses: actions/upload-artifact@v3
        with:
          name: archive
          path: |
            app/android/build/outputs/apk/debug/*
            app/android/build/outputs/bundle/release/*.aab

      - name: Upload Android Release to Play Store - Internal track
        uses: r0adkll/upload-google-play@v1.0.17
        with:
          status: draft
          track: internal
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          packageName: studio.forface.cinescout2
          releaseFiles: app/android/build/outputs/bundle/release/*.aab
