name: Run Tests and deploy

on:
  push:
    branches:
      - 'main'

jobs:

  setup:
    name: Setup project
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  dependencies:
    name: Update dependencies
    uses: ./.github/workflows/dependencies.yml
    secrets: inherit

  detekt:
    name: Analyze with Detekt
    uses: ./.github/workflows/analyze.yml
    secrets: inherit

  all-tests:
    name: Tests
    needs: setup
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  build:
    name: Build
    needs: setup
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    name: Deploy
    needs:
      - all-tests
      - build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
