name: Deploy apps

on: workflow_call

jobs:

  deploy:

    name: Deploy Android app to Play Store
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download Release archive
        uses: actions/upload-artifact@v3
        with:
          name: archive

      - name: Create google-services json
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | base64 -d > ${GITHUB_WORKSPACE}/app/android/google-services.json

      - name: Upload Android Release to Play Store - Internal track
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          track: internal
          serviceAccountJson: app/android/google-services.json
          packageName: studio.forface.cinescout2
          releaseFiles: app/android/build/outputs/bundle/release/*.aab
