name: Instrumented tests

on: workflow_call

jobs:

  instrumented-tests:

    name: Instrumented tests
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache Android build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ~/
          key: ci-android-build${{ github.sha }}

      - name: Create Firebase Service Account json
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > ${GITHUB_WORKSPACE}/ftl-credentials.json

      - name: Run Flank
        run: ./gradlew flankRun --stacktrace
