name: Instrumented tests

on: workflow_call

jobs:

  instrumented-tests:

    name: Instrumented tests
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache Android build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ~/
          key: ci-android-build${{ github.sha }}

      - name: Create Firebase Service Account json
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > ${GITHUB_WORKSPACE}/fsa.json

      - name: Assemble debug APK
        run: ./gradlew assembleDebug

      - name: Assemble Android tests APK
        run: ./gradlew assembleDebugAndroidTest

      - name: Flank
        uses: Flank/flank@v23.03.0
        with:
          service_account: './fsa.json'
          platform: android
          flank_configuration_file: '.flank/config.yml'

      - name: output
        run: |
          # Use local directory output
          echo "Local directory: ${{ steps.flank_run.outputs.local_results_directory }}"
