name: Push Workflow

on:
  push:
    branches-ignore:
      - 'main'

jobs:

  setup:
    name: Setup project
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  detekt:
    name: Analyze with Detekt
    uses: ./.github/workflows/analyze.yml
    secrets: inherit

  tests:
    name: Tests
    needs: setup
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  instrumented-tests:
    name: Instrumented tests app
    needs: setup
    uses: ./.github/workflows/instrumented-tests.yml
    secrets: inherit
