name: Run Tests

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run all tests
        uses: .github/workflows/tests.yml
