name: Setup

on: workflow_call

jobs:

  setup:

    name: Setup project
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache Android build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ github.workspace }}/gradle.properties
            ${{ github.workspace }}/app/android/google-services.json
            ${{ github.workspace }}/cinescout/network/tmdb/src/commonMain/kotlin/cinescout/network/tmdb/tmdbKeys.kt
            ${{ github.workspace }}/cinescout/network/trakt/src/commonMain/kotlin/cinescout/network/trakt/traktKeys.kt
          key: cache-${{ github.ref }}
          restore-keys: |
            cache-${{ github.ref }}
            cache-${{ github.base_ref }}
            cache-

      - name: Setup Gradle properties
        run: |
          echo "${{ secrets.GRADLE_PROPERTIES }}" | base64 -d > ${GITHUB_WORKSPACE}/gradle.properties
          mkdir build

      - name: Create google-services json
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | base64 -d > ${GITHUB_WORKSPACE}/app/android/google-services.json

      - name: Setup API keys
        run: |
          echo "${{ secrets.TMDB_KEYS_BASE64 }}" | base64 -d > "${GITHUB_WORKSPACE}"/cinescout/network/tmdb/src/commonMain/kotlin/cinescout/network/tmdb/tmdbKeys.kt &&
          echo "${{ secrets.TRAKT_KEYS_BASE64 }}" | base64 -d > "${GITHUB_WORKSPACE}"/cinescout/network/trakt/src/commonMain/kotlin/cinescout/network/trakt/traktKeys.kt
