name: Tests

on: workflow_call

jobs:

  database:

    name: Verify database
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Cache Android build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ github.workspace }}/gradle.properties
            ${{ github.workspace }}/app/android/google-services.json
            ${{ github.workspace }}/cinescout/network/tmdb/src/commonMain/kotlin/cinescout/network/tmdb/tmdbKeys.kt
            ${{ github.workspace }}/cinescout/network/trakt/src/commonMain/kotlin/cinescout/network/trakt/traktKeys.kt
          key: cache-${{ github.ref }}-test-database
          restore-keys: |
            cache-${{ github.ref }}
            cache-${{ github.base_ref }}

      - name: Verify Database Migrations
        run: ./gradlew verifySqlDelightMigration

  multiplatform-tests:

    name: Multiplatform tests
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Cache Android build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ github.workspace }}/gradle.properties
            ${{ github.workspace }}/app/android/google-services.json
            ${{ github.workspace }}/cinescout/network/tmdb/src/commonMain/kotlin/cinescout/network/tmdb/tmdbKeys.kt
            ${{ github.workspace }}/cinescout/network/trakt/src/commonMain/kotlin/cinescout/network/trakt/traktKeys.kt
          key: cache-${{ github.ref }}-test-multiplatform
          restore-keys: |
            cache-${{ github.ref }}
            cache-${{ github.base_ref }}

      - name: Run Jvm Tests
        run: ./gradlew jvmTest

  android-junit-tests:

    name: Android Junit tests
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Cache Android build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ github.workspace }}/gradle.properties
            ${{ github.workspace }}/app/android/google-services.json
            ${{ github.workspace }}/cinescout/network/tmdb/src/commonMain/kotlin/cinescout/network/tmdb/tmdbKeys.kt
            ${{ github.workspace }}/cinescout/network/trakt/src/commonMain/kotlin/cinescout/network/trakt/traktKeys.kt
          key: cache-${{ github.ref }}-test-android-junit
          restore-keys: |
            cache-${{ github.ref }}
            cache-${{ github.base_ref }}

      - name: Run Jvm Tests
        run: ./gradlew test
