name: Test

on: [push]

jobs:

  Unit-tests:

    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run Jvm Tests
        run: ./gradlew jvmTest --continue

  Database:

    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Verify Database Migrations
        run: ./gradlew verifySqlDelightMigration
